package frc.robot.challenges;

import java.util.Random;

/**
 * Easy challenge harness. Builds 1000 rooms, picks a random winning room, and
 * runs the player's {@link EasySolution#solve(Room[])}. Do not edit this file —
 * write your loop in EasySolution.
 */
public final class EasyChallenge {
  private EasyChallenge() {}

  public static void run() {
    // The winning room: random, over 200 and under 1000.
    int trigger = 201 + new Random().nextInt(799); // 201..999
    Room.begin(trigger);

    Room[] rooms = new Room[1000];
    for (int i = 0; i < rooms.length; i++) {
      rooms[i] = new Room(i);
    }

    EasySolution.solve(rooms);

    if (Room.checkedCount == 0) {
      System.out.println("(You didn't check any rooms. Loop over the rooms and "
          + "call check() on each — start at the 100th.)");
    }
  }
}
