package frc.robot.challenges;

import edu.wpi.first.wpilibj.Filesystem;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.regex.Pattern;

/**
 * Medium challenge harness. Loads the 100-page book from the deploy directory,
 * hands it to the player's {@link MediumSolution#solve(String[])}, and checks
 * the phrase they return. Do not edit this file — write your loop in
 * MediumSolution.
 */
public final class MediumChallenge {
  private MediumChallenge() {}

  // Pages are joined by this sentinel line in book.txt (see make_book.py).
  private static final String DELIMITER = "\n~~~\n";
  private static final String ANSWER = "Swerve Drive Kinematics";
  private static final String PASSWORD = "Holonomic Drive";

  public static void run() {
    String[] book = loadBook();
    if (book == null) {
      return;  // loadBook already printed the reason.
    }

    String answer = MediumSolution.solve(book);

    if (answer == null || answer.isBlank()) {
      System.out.println("(You returned nothing. Print the pages, find the three "
          + "words the book hides, and return them as one phrase.)");
      return;
    }

    if (answer.trim().equalsIgnoreCase(ANSWER)) {
      System.out.println(PASSWORD);
    } else {
      System.out.println("That's not the phrase. Read the pages again — two of "
          + "them are real.");
    }
  }

  /** Read book.txt from the deploy dir and split it into pages, or null on error. */
  private static String[] loadBook() {
    Path bookFile = Filesystem.getDeployDirectory().toPath().resolve("book.txt");
    try {
      String raw = Files.readString(bookFile);
      return raw.split(Pattern.quote(DELIMITER), -1);
    } catch (IOException e) {
      System.out.println("Could not read the book at " + bookFile
          + " — run make_book.py to generate it.");
      return null;
    }
  }
}
